### ISSUE TITLE
Consider separate youtube channel

### ISSUE THREAD

**Issue by ilblackdragon** [near/devrel#279]
NEAR youtube channel has lots of different content.
A more consistent channel for developers might be attracting more followers.

**Comment by zavodil** [comment]
I agree. The only concern: huge Youtube channel has an advantage for Youtube's recommendations. Thus, videos from the main channel has the best chances to reach our potential audience inside the YouTube Platform.

Did we already separate channel for sync daily calls?

**Comment by chadlamon** [comment]
I highly agree with this @ilblackdragon! Ill create a youtube channel for BlockHeads tomorrow & see what kind of metrics we receive.

**Comment by chadlamon** [comment]
@zavodil I agree with what you're saying, your concern is why I haven't created a whole other youtube channel because we would be starting from scratch. 

Ill do a case study with creating another youtube channel & everyone at NEAR can upload Blockchain specific content only & would be allowed to premier one video per day at a scheduled time for consistency. 

I feel like its about time for me to create a NEAR youtube etiquette google doc / video tutorial, would you two be interested in me doing something like this?
